### ISSUE TITLE
RobotContainer Cleanup

### ISSUE THREAD

**Issue by Jacob4649** [FRC4946/2020Robot#85]

**Comment by Jacob4649** [comment]
Remove unneeded references to buttons, chain whileHeld and whenPressed etc... to assign commands

**Comment by matthew-reynolds** [comment]
Also move more complicated or re-used commands into full classes rather than inline.

**Comment by Jacob4649** [comment]
> Also move more complicated or re-used commands into full classes rather than inline.

Gonna do this in a later PR, I probably should've named this one better
